name: Wails build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: AeroMod
          build-platform: windows/amd64
          go-version: 1.22
          node-version: 21
